name: CUDA-Q build

on:
  workflow_call:
    inputs:
      cache_key_suffix:
        type: string
        default: ''
        required: false
      save_build:
        type: boolean
        default: true
        required: false
      save_ccache:
        type: boolean
        default: false
        required: false
      cudaq_repo:
        type: string
        default: ''
        required: false
      cudaq_ref:
        type: string
        default: ''
        required: false
    secrets:
      CUDAQ_ACCESS_TOKEN:
        required: false

jobs:
  build-cudaq:
    name: Build CUDA-Q
    strategy:
      fail-fast: false
      matrix:
        platform: ['amd64', 'arm64']
        cuda_version: ['12.6', '13.0']
    runs-on: ${{ startsWith(github.repository, 'NVIDIA/cudaq-algorithms') && format('linux-{0}-cpu32', matrix.platform) || 'ubuntu-latest' }}
    container: ghcr.io/nvidia/cuda-quantum-devcontainer:${{ matrix.platform }}-cu${{ matrix.cuda_version }}-gcc12-main
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Configure
        id: config
        run: |
          cuda_major=$(echo ${{ matrix.cuda_version }} | cut -d . -f1)
          echo "cuda_major=$cuda_major" >> "$GITHUB_OUTPUT"

      - name: Get required CUDAQ version
        id: get-cudaq-version
        uses: ./.github/actions/get-cudaq-version
        with:
          repo: ${{ inputs.cudaq_repo }}
          ref: ${{ inputs.cudaq_ref }}

      - name: Get CUDAQ build
        uses: ./.github/actions/get-cudaq-build
        with:
          repo: ${{ steps.get-cudaq-version.outputs.repo }}
          ref: ${{ steps.get-cudaq-version.outputs.ref }}
          token: ${{ secrets.CUDAQ_ACCESS_TOKEN }}
          cache-key-suffix: ${{ inputs.cache_key_suffix }}
          save-build: ${{ inputs.save_build }}
          save-ccache: ${{ inputs.save_ccache }}
          platform: ${{ matrix.platform }}-cu${{ steps.config.outputs.cuda_major }}
